import { useState } from 'react';
import { ApiError, errorFromResponse, type Job } from '@gkd/client';
import { Badge, dateLabel, Empty, ErrorNote, Field, Icon, Loading, useOperation, useResource, useUI, waitForJob } from './ui';

export function SearchPanel() {
  const { api, epoch, openCapture, openGroup } = useUI();
  const [text, setText] = useState(''), [query, setQuery] = useState(''), [kind, setKind] = useState('');
  const [offset, setOffset] = useState(0);
  const result = useResource(() => query ? api.search(query, { kind: kind || null, offset, limit: 25 }) : Promise.resolve({ items: [], total: 0, offset: 0, limit: 25 }), `${epoch}:${query}:${kind}:${offset}`);
  return <><section className="page-heading"><div><h1>找到你留下的线索。</h1><p>搜索任务、Markdown 正文与原始记录。支持中文关键词。</p></div></section><form className="search-form" onSubmit={e => { e.preventDefault(); setQuery(text.trim()); setOffset(0); }}><Icon name="search" size={22} /><input aria-label="搜索关键词" value={text} maxLength={200} onChange={e => setText(e.target.value)} placeholder="输入标题、任务或原文中的关键词" /><button className="primary" type="submit" disabled={!text.trim()}>搜索</button></form><div className="filter-tabs search-filters">{[['', '全部'], ['task', '任务'], ['group', '任务组'], ['capture', '原始记录']].map(([key, label]) => <button key={key} aria-pressed={kind === key} onClick={() => { setKind(key); setOffset(0); }}>{label}</button>)}</div>
    <ErrorNote error={result.error} retry={result.reload} />{result.loading && query ? <Loading /> : !query ? <Empty title="记得一点线索就够了。">输入词语，找回它所在的任务、文件或原文。</Empty> : !result.error && result.data?.total === 0 ? <Empty title="没有找到匹配内容。">试试更短的词语，或切换对象类型。</Empty> : <><div className="section-heading"><h2>搜索结果</h2><span className="small-muted">{result.data?.total} 项</span></div><div className="search-results">{result.data?.items.map(hit => <button className="search-hit" key={`${hit.type}:${hit.id}`} onClick={() => hit.type === 'capture' ? openCapture(hit.id) : openGroup(hit.group_id || hit.id)}><span className="search-kind">{{ task: 'TASK', group: 'MARKDOWN', capture: 'CAPTURE' }[hit.type]}</span><strong>{hit.title}</strong><span>{hit.snippet}</span><Icon name="arrow" size={16} /></button>)}</div></>}
    {result.data && result.data.total > 25 && <div className="pagination"><button disabled={!offset} onClick={() => setOffset(offset - 25)}>上一页</button><span>{offset + 1} / {result.data.total}</span><button disabled={offset + 25 >= result.data.total} onClick={() => setOffset(offset + 25)}>下一页</button></div>}
  </>;
}

function sizeLabel(bytes: number) { return bytes < 1024 ? `${bytes} B` : bytes < 1024 ** 2 ? `${(bytes / 1024).toFixed(1)} KiB` : bytes < 1024 ** 3 ? `${(bytes / 1024 ** 2).toFixed(1)} MiB` : `${(bytes / 1024 ** 3).toFixed(1)} GiB`; }

export function SettingsPanel({ onLogout }: { onLogout: () => void }) {
  const { api, auth, profile, epoch, refresh, notify, openCapture, openGroup } = useUI();
  const [name, setName] = useState(profile?.workspace.name || auth.workspace.name);
  const [timezone, setTimezone] = useState(profile?.workspace.timezone || auth.workspace.timezone);
  const [aiEnabled, setAiEnabled] = useState(profile?.workspace.ai_enabled || false);
  const [history, setHistory] = useState(false);
  const [tab, setTab] = useState('trash');
  const [job, setJob] = useState<Job | null>(null);
  const operation = useOperation();
  const records = useResource(async () => ({ groups: await api.groups({ trash: tab === 'trash', status: tab === 'archive' ? 'archived' : null, limit: 100 }), captures: await api.captures({ trash: tab === 'trash', status: tab === 'archive' ? 'archived' : null, limit: 100 }) }), `${epoch}:${tab}`);
  const jobs = useResource(api.jobs, epoch);
  async function download(job: Job) {
    if (!job.result?.download_url) throw new ApiError('EXPORT_UNAVAILABLE', '导出尚未完成。');
    const response = await fetch(job.result.download_url, { headers: { Authorization: `Bearer ${auth.token}` } });
    if (!response.ok) throw errorFromResponse(response.status, await response.json().catch(() => null));
    const blob = await response.blob(); const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'guike-export.zip';
    document.body.appendChild(anchor); anchor.click(); anchor.remove(); setTimeout(() => URL.revokeObjectURL(url), 30000);
    notify('导出包已生成，包含内容清单和校验和。');
  }
  return <><section className="page-heading"><div><h1>让工具，按你的方式工作。</h1><p>数据处理有边界，存储内容可追溯，也可带走。</p></div><span className="large-avatar">{auth.user.display_name.slice(0, 1)}</span></section>
    <div className="settings-grid"><section className="settings-section"><h2>你的工作空间</h2><p className="muted">{auth.user.display_name} · {auth.user.username}</p><form onSubmit={e => { e.preventDefault(); void operation.run(async () => { await api.updateWorkspace({ name, timezone }); refresh(); notify('工作空间设置已保存。已有任务的时区不会被改写。'); }); }}><Field label="工作空间名称"><input value={name} onChange={e => setName(e.target.value)} required maxLength={80} /></Field><Field label="默认时区" hint="仅用于新任务与分析；不修改已有时间的语义。"><input list="timezones" value={timezone} onChange={e => setTimezone(e.target.value)} required /><datalist id="timezones">{['Asia/Shanghai', 'Asia/Tokyo', 'UTC', 'Europe/London', 'America/New_York'].map(t => <option key={t} value={t} />)}</datalist></Field><button type="submit" disabled={operation.busy}>保存设置</button></form></section>
    <section className="settings-section"><h2>外部 AI 与数据授权</h2><span className="badge status-next">{profile?.ai.configured ? '已配置供应商' : '未配置 · 本地规则可用'}</span><p className="muted">{profile?.ai.provider || '未配置'}{profile?.ai.model ? ` / ${profile.ai.model}` : ''}</p><p className="disclosure-text">{profile?.ai.disclosure || '仅发送当前原文及必要的参照信息；不会上传整个工作空间。'}</p><label className="check-label consent"><input type="checkbox" checked={aiEnabled} disabled={!profile?.ai.configured || operation.busy} onChange={e => setAiEnabled(e.target.checked)} /><span>我已阅读上述范围，允许发送所选记录到外部 AI</span></label><div className="button-row"><button disabled={operation.busy || !profile || (aiEnabled && !profile.ai.configured)} onClick={() => void operation.run(async () => { await api.updateWorkspace({ ai_enabled: aiEnabled, ai_consent_version: profile!.ai.consent_version }); refresh(); notify(aiEnabled ? '外部 AI 已启用，仍需逐次选择整理方式。' : '外部 AI 已关闭。'); })}>保存授权选择</button><span className="small-muted">今日 {profile?.ai.usage.requests ?? 0} / {profile?.ai.usage.limit ?? '—'} 次</span></div></section>
    <section className="settings-section"><h2>导出与存储</h2><p className="storage-value">{profile ? sizeLabel(profile.storage.bytes) : '—'} <span>/ {profile ? sizeLabel(profile.storage.limit) : '—'}</span></p><p className="muted">导出 Markdown、原始 Capture 和校验清单，不包含密码或会话。导出包 24 小时失效。</p><label className="check-label"><input type="checkbox" checked={history} onChange={e => setHistory(e.target.checked)} />附带历史版本与操作记录</label><button className="primary" disabled={operation.busy} onClick={() => void operation.run(async () => { const queued = await api.export(history); setJob(queued); const result = await waitForJob(api, queued.id, setJob); refresh(); await download(result); })}>导出我的内容</button><p className="small-muted">内容导出不是完整系统备份。账户与操作数据库的备份方式见仓库 README。</p></section>
    <section className="settings-section"><h2>索引与服务</h2><p>任务和文件内容保存在 Markdown 中。查询索引可以重新生成，不会改写原文件。</p><button disabled={operation.busy} onClick={() => void operation.run(async () => { const queued = await api.rebuildIndex(); setJob(queued); const result = await waitForJob(api, queued.id, setJob); refresh(); notify(`索引已重建：${result.result?.groups} 个文件，${result.result?.tasks} 项任务。`); })}>检查并重建索引</button><p className="small-muted">损坏文件会单独报告，不会自动修复或覆盖。大规模性能与正式发布验收尚待完成。</p></section></div>
    {job && <div className="job-progress"><Badge status={job.status} /><span>{{ analysis: '整理记录', export: '导出内容', reindex: '重建索引' }[job.kind]}</span>{job.result?.errors?.map(error => <p className="danger-text" key={error.path}>{error.path}：{error.message}</p>)}</div>}<ErrorNote error={operation.error} />
    <section className="settings-records"><div className="section-heading"><h2>保留与恢复</h2><div className="filter-tabs"><button aria-pressed={tab === 'trash'} onClick={() => setTab('trash')}>回收站</button><button aria-pressed={tab === 'archive'} onClick={() => setTab('archive')}>已归档</button></div></div><p className="small-muted">当前 MVP 保留这些内容，支持恢复。永久删除与自动留存清理不在本次交付范围。</p><ErrorNote error={records.error} retry={records.reload} />{records.loading && !records.data ? <Loading /> : records.data && !records.data.groups.total && !records.data.captures.total ? <p className="empty-inline">这里没有内容。</p> : <div className="retained-list">{records.data?.groups.items.map(g => <div className="retained-row" key={g.id}><Icon name="file" size={18} /><span><strong>{g.title}</strong><small>任务组 · {g.tasks.length} 项任务</small></span>{tab === 'archive' && <button onClick={() => openGroup(g.id)}>查看</button>}<button disabled={operation.busy} onClick={() => void operation.run(async () => { const change = tab === 'trash' ? await api.restoreGroup(g) : await api.updateGroup(g.id, { expected_revision: g.revision, expected_hash: g.content_hash, status: 'active' }); refresh(); notify('任务组已恢复。', change); })}>恢复任务组</button></div>)}{records.data?.captures.items.map(c => <div className="retained-row" key={c.id}><Icon name="inbox" size={18} /><span><strong>{c.integrity_error ? '原文损坏或不可用，文件未被改写。' : c.raw_text.slice(0, 100)}</strong><small>原始记录 · {dateLabel(c.created_at)}{c.integrity_error && ` · ${c.integrity_error.message}`}</small></span>{tab === 'archive' && !c.integrity_error && <button onClick={() => openCapture(c.id)}>查看</button>}<button disabled={operation.busy} onClick={() => void operation.run(async () => { const capture = await api.captureState(c.id, tab === 'trash' ? 'restore' : 'unarchive'); refresh(); notify(capture.integrity_error ? '记录已恢复，原文仍不可用；请从备份检查原始文件。' : '原始记录已恢复。'); })}>{c.integrity_error ? '恢复记录（原文仍不可用）' : '恢复原文'}</button>{tab === 'archive' && c.integrity_error && <button disabled={operation.busy} onClick={() => void operation.run(async () => { if (!window.confirm('将不可用记录移入回收站？原始文件会保留，其他任务不受影响。')) return; await api.captureState(c.id, 'trash'); refresh(); notify('不可用记录已移入回收站，原始文件仍保留。'); })}>移入回收站</button>}</div>)}</div>}</section>
    <section className="settings-records"><h2>最近的后台任务</h2><ErrorNote error={jobs.error} retry={jobs.reload} />{jobs.data?.length === 0 && <p className="empty-inline">还没有后台任务。</p>}{jobs.data?.slice(0, 10).map(j => <div className="retained-row" key={j.id}><span><strong>{{ analysis: '整理记录', export: '导出内容', reindex: '重建索引' }[j.kind]}</strong><small>{dateLabel(j.created_at)}{j.error ? ` · ${j.error.message}` : ''}</small></span><Badge status={j.status} />{j.status === 'succeeded' && j.kind === 'export' && <button disabled={operation.busy} onClick={() => void operation.run(() => download(j))}>下载</button>}{(j.status === 'pending' || j.status === 'running') && <button disabled={operation.busy} onClick={() => void operation.run(async () => { await waitForJob(api, j.id, setJob); refresh(); notify('后台任务已结束。'); })}>查看进度</button>}</div>)}</section>
    <div className="logout-row"><div><strong>退出账号</strong><p>界面会清除当前账号数据。本机待上传草稿仅在此账号下保留。</p></div><button disabled={operation.busy} onClick={() => void operation.run(async () => { try { await api.logout(); } catch { window.alert('服务端未连接。本机将退出，服务端会话会在到期后失效。'); } finally { onLogout(); } })}>退出登录</button></div>
  </>;
}
